import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Audit Disclaimer | AuditAI by Yample Labs',
  description: 'Important disclaimer regarding AI-generated audit reports, score interpretations, and limitations of AuditAI platform.',
}

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#08080f] text-white">
      <div className="border-b border-white/5 px-6 py-4 flex items-center justify-between max-w-7xl mx-auto">
        <Link href="/" className="text-white/60 hover:text-white transition-colors text-sm">← Back to Home</Link>
        <span className="text-xs font-mono text-violet-300 uppercase tracking-wider">Disclaimer</span>
      </div>
      <div className="max-w-4xl mx-auto px-6 py-12 space-y-10 text-slate-300 text-sm leading-relaxed">
        <div className="space-y-3 pb-8 border-b border-white/10">
          <span className="text-xs font-mono text-violet-400 uppercase tracking-widest">Yample Labs Legal</span>
          <h1 className="text-3xl md:text-4xl font-black text-white">Audit & Platform Disclaimer</h1>
          <p className="text-xs text-slate-500 font-mono">Last Updated: August 7, 2026</p>
        </div>

        <div className="bg-amber-950/20 border border-amber-500/30 rounded-xl p-5 space-y-2">
          <div className="text-amber-300 font-bold text-sm">⚠️ Important Notice</div>
          <p>Please read this disclaimer carefully before relying on any audit report, score, recommendation, or business analysis generated by AuditAI. By using this platform, you acknowledge and agree to the limitations described below.</p>
        </div>

        {[
          {
            num: 1,
            title: 'Nature of AI-Generated Reports',
            content: `AuditAI reports are generated by automated AI systems that analyze publicly accessible website data. These reports are informational in nature and represent a point-in-time technical assessment. They are NOT professional consulting advice, legal opinions, financial assessments, or guarantees of business performance.

The AI models used by AuditAI are trained on publicly available SEO, performance, and security standards. While we continuously improve our models, AI-generated insights may contain inaccuracies, errors, or outdated information.`
          },
          {
            num: 2,
            title: 'Score Limitations',
            content: `Website scores (Performance, SEO, Security, Accessibility) generated by AuditAI are composite metrics based on technical signals available at the time of the scan. These scores:
- May differ from scores generated by Google PageSpeed, GTmetrix, or other tools due to different methodologies.
- Do not reflect real-time user experience or server-side performance.
- Can fluctuate based on server load, CDN status, and third-party scripts at scan time.
- Are NOT official Google or search engine metrics.

A high AuditAI score does not guarantee top search rankings. SEO is influenced by many factors beyond technical on-page metrics.`
          },
          {
            num: 3,
            title: 'Revenue & Business Intelligence Estimates',
            content: `Any revenue impact estimates, competitor analysis insights, or business growth projections provided in AuditAI reports are educated estimations based on general industry data and technical metrics. They are NOT financial forecasts, guarantees of revenue increase, or professional business valuations.

Yample Labs makes no representation that implementing our recommendations will result in specific revenue growth, traffic increases, or conversion rate improvements.`
          },
          {
            num: 4,
            title: 'Third-Party Data',
            content: `AuditAI integrates with Google PageSpeed Insights API, Lighthouse, and other third-party services. The availability, accuracy, and continuity of data from these services is outside our control. We are not responsible for inaccuracies in data sourced from third-party APIs.`
          },
          {
            num: 5,
            title: 'Security Audit Scope',
            content: `Security assessments performed by AuditAI cover publicly observable technical signals (HTTP headers, SSL configuration, publicly known vulnerabilities). They do NOT constitute a professional penetration test, vulnerability assessment, or security audit. For critical security decisions, engage a certified cybersecurity professional.`
          },
          {
            num: 6,
            title: 'No Warranty',
            content: `The AuditAI platform and all reports are provided "AS IS" without warranty of any kind — express or implied — including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. Use of our platform and reliance on our reports is at your own risk.`
          },
          {
            num: 7,
            title: 'Competitor Data',
            content: `Competitor analysis features display publicly available technical data about third-party websites. This data is used for comparative benchmarking purposes only. We are not affiliated with, endorsed by, or partnered with any competitor website featured in our analysis.`
          },
        ].map(({ num, title, content }) => (
          <section key={num} className="space-y-3">
            <h2 className="text-xl font-bold text-white flex items-center gap-3">
              <span className="w-7 h-7 rounded-lg bg-violet-600/30 border border-violet-500/30 text-violet-300 text-xs font-mono flex items-center justify-center flex-shrink-0">{num}</span>
              {title}
            </h2>
            <div className="pl-10">
              {content.split('\n').filter(l => l.trim()).map((line, i) => {
                if (line.startsWith('- ')) {
                  return <li key={i} className="ml-4 list-disc">{line.slice(2)}</li>
                }
                return <p key={i} className="mb-2">{line}</p>
              })}
            </div>
          </section>
        ))}

        <div className="bg-white/[0.02] border border-white/10 rounded-xl p-5">
          <p className="font-bold text-white mb-2">Questions About This Disclaimer?</p>
          <p>Contact us at <strong className="text-violet-400">yamplelabs@gmail.com</strong> | Yample Labs, India</p>
        </div>
      </div>
    </div>
  )
}
