'use client'

import { useState } from 'react'
import Link from 'next/link'
import { QuickAuditModal } from '@/components/dashboard/QuickAuditModal'

export default function LandingPage() {
  const [isAuditModalOpen, setIsAuditModalOpen] = useState(false)
  const [activeFaq, setActiveFaq] = useState<number | null>(null)

  const whatAuditAiDoes = [
    { title: 'Website Performance Analysis', desc: 'Deep-dive Core Web Vitals audit (LCP, CLS, INP, TTFB, Speed Index).', icon: '⚡' },
    { title: 'SEO Analysis', desc: 'On-page title tags, meta descriptions, heading hierarchy, robots.txt, sitemaps.', icon: '🔍' },
    { title: 'Accessibility Analysis', desc: 'WCAG AA compliance scanner evaluating contrast, ARIA landmarks, and alt tags.', icon: '♿' },
    { title: 'Security Analysis', desc: 'HTTPS SSL certification, CSP, HSTS, X-Frame-Options, and security headers.', icon: '🛡️' },
    { title: 'Business Growth Analysis', desc: 'Conversion rate friction detection and quantitative revenue uplift modeling.', icon: '📈' },
    { title: 'AI Recommendations', desc: 'Prioritized action plans generated by specialized Claude & OpenAI models.', icon: '🤖' },
    { title: 'Professional PDF Reports', desc: 'Client-ready executive reports branded with Yample Labs identity.', icon: '📄' },
  ]

  const whyChooseYampleLabs = [
    { title: 'AI-Powered Analysis', desc: 'Multi-provider AI router providing deep data-driven recommendations.' },
    { title: 'Premium UI/UX', desc: 'Enterprise SaaS aesthetic crafted with Geist typography and dark mode elegance.' },
    { title: 'Modern Technology', desc: 'Built on Next.js 16, Supabase PostgreSQL, TypeScript, and Turbopack.' },
    { title: 'Business-Focused Solutions', desc: 'Every line of code is optimized to increase client revenue and conversions.' },
    { title: 'Transparent Pricing', desc: 'Fixed package rates ($599 Starter, $1,999 Professional) with no hidden fees.' },
    { title: 'Scalable Architecture', desc: 'Monorepo architecture engineered for enterprise scalability.' },
    { title: 'Long-Term Support', desc: 'Continuous monitoring, regression prevention, and dedicated technical care.' },
  ]

  const ourServices = [
    { title: 'Website Upgrade', desc: 'Performance acceleration, Core Web Vitals fixes, and modern UI overhaul.', tag: 'Popular' },
    { title: 'Custom Website Development', desc: 'Bespoke Next.js & React web platforms engineered for max conversions.' },
    { title: 'AI Automation', desc: 'Custom AI assistants, lead qualification bots, and workflow automation.' },
    { title: 'Web Applications', desc: 'Scalable full-stack SaaS web applications powered by Supabase PostgreSQL.' },
    { title: 'Mobile Apps', desc: 'Cross-platform mobile application development for iOS and Android.' },
    { title: 'SaaS Development', desc: 'End-to-end multi-tenant SaaS architecture, RLS security, and billing integration.' },
  ]

  const pricingTiers = [
    {
      name: 'Starter',
      price: '$599',
      subtext: 'Ideal for small businesses needing immediate performance & SEO upgrades.',
      features: [
        'Complete AuditAI Analysis',
        'Website Performance Acceleration',
        'On-Page SEO Overhaul',
        'WCAG AA Accessibility Fixes',
        'Professional PDF Report',
        '24/7 AI Assistant (Basic Support)',
        '30-Day Technical Warranty',
      ],
      cta: 'Choose Starter Plan',
      isPopular: false,
    },
    {
      name: 'Professional',
      price: '$1,999',
      subtext: 'Comprehensive growth engine for ambitious agencies & scaling businesses.',
      features: [
        'Everything in Starter Plan',
        'Full Custom Website Redesign',
        'Advanced AI Assistant (Order & FAQ Support)',
        'Lead Ingestion & CRM Integration',
        'WhatsApp Business Qualification Flow',
        'Security Header Hardening',
        'Revenue Opportunity Optimization',
        '60-Day Dedicated Agency Support',
      ],
      cta: 'Choose Professional Plan',
      isPopular: true,
    },
    {
      name: 'Enterprise',
      price: 'Custom Quote',
      subtext: 'Tailored full-stack SaaS development, custom AI models, and dedicated engineering.',
      features: [
        'Bespoke Web & Mobile App Development',
        'Multi-Tenant SaaS Architecture',
        'Custom AI Engine & LLM Fine-Tuning',
        'Dedicated Project Engineering Team',
        'SLA & 24/7 Priority Hotline',
      ],
      cta: 'Request Enterprise Quote',
      isPopular: false,
    },
  ]

  const aiAssistantFeatures = [
    { title: '24/7 Customer Support', desc: 'Instantly answers visitor questions round the clock.' },
    { title: 'Lead Collection', desc: 'Captures visitor contact info and qualifies sales leads.' },
    { title: 'FAQ Answers', desc: 'Provides automated answers based on your business knowledgebase.' },
    { title: 'Appointment Support', desc: 'Schedules consultations directly into your agency calendar.' },
    { title: 'Order Support', desc: 'Tracks order status and answers customer inquiries (Professional Plan).' },
    { title: 'CRM Integration', desc: 'Syncs lead data directly to your CRM pipeline (Professional/Enterprise).' },
  ]

  const ourProcess = [
    { step: '01', title: 'Audit', desc: 'Run AuditAI to scan performance, SEO, accessibility, and security.' },
    { step: '02', title: 'Analysis', desc: 'AI Router identifies revenue bottlenecks and technical debt.' },
    { step: '03', title: 'Proposal', desc: 'We deliver a clear scope of work, fixed pricing, and timeline.' },
    { step: '04', title: 'Development', desc: 'Yample Labs engineers implement code optimizations and modern UI.' },
    { step: '05', title: 'Launch', desc: 'Deploy optimized platform to production with zero downtime.' },
    { step: '06', title: 'Growth', desc: 'Continuous monitoring and AI lead automation to scale revenue.' },
  ]

  const faqs = [
    {
      q: 'How does AuditAI work?',
      a: 'AuditAI scans your website URL across Google PageSpeed Insights, Lighthouse, WCAG AA compliance, on-page SEO crawlers, and security header auditors. Our AI Router then synthesizes empirical data into actionable executive recommendations.',
    },
    {
      q: 'How long does website development or upgrade take?',
      a: 'Starter upgrades ($599) are completed within 5-7 business days. Professional projects ($1,999) typically take 2-3 weeks.',
    },
    {
      q: 'What is included in the AI Assistant?',
      a: 'The AI Assistant provides 24/7 automated customer support, lead capture, appointment booking, and CRM synchronization.',
    },
    {
      q: 'What is included in Yample Labs services?',
      a: 'We offer full-stack Next.js web development, SaaS product engineering, custom AI automation, mobile apps, and technical SEO overhauls.',
    },
    {
      q: 'How do I get technical support?',
      a: 'You can reach out directly via email at yamplelabs@gmail.com, Instagram @yamplelabs, GitHub @manish63018-sketch, or message support handle @mannish_2323.',
    },
  ]

  return (
    <div className="min-h-screen bg-background text-text-primary selection:bg-brand selection:text-white">
      {/* Navigation Bar */}
      <header className="sticky top-0 z-40 w-full border-b border-border/80 bg-background/80 backdrop-blur-md">
        <div className="max-w-7xl mx-auto flex h-16 items-center justify-between px-6">
          <Link href="/" className="flex items-center space-x-3">
            <div className="h-8 w-8 rounded-lg bg-brand flex items-center justify-center font-bold text-white shadow-md shadow-brand/20">
              A
            </div>
            <div>
              <span className="font-bold text-lg text-text-primary tracking-tight block leading-none">
                AuditAI
              </span>
              <span className="text-[10px] text-brand font-semibold tracking-wider uppercase">
                Yample Labs
              </span>
            </div>
          </Link>

          <nav className="hidden md:flex items-center space-x-8 text-xs font-semibold text-text-muted">
            <a href="#about" className="hover:text-text-primary transition-colors">What It Does</a>
            <a href="#services" className="hover:text-text-primary transition-colors">Services</a>
            <a href="#pricing" className="hover:text-text-primary transition-colors">Pricing</a>
            <a href="#ai-assistant" className="hover:text-text-primary transition-colors">AI Assistant</a>
            <a href="#process" className="hover:text-text-primary transition-colors">Process</a>
            <Link href="/case-studies" className="hover:text-text-primary transition-colors">Case Studies</Link>
            <a href="#contact" className="hover:text-text-primary transition-colors">Contact</a>
          </nav>

          <div className="flex items-center space-x-3">
            <Link href="/login" className="text-xs font-semibold text-text-muted hover:text-text-primary px-3 py-2">
              Sign In
            </Link>
            <button
              onClick={() => setIsAuditModalOpen(true)}
              className="px-4 py-2 rounded-lg bg-brand text-white text-xs font-semibold hover:bg-brand-hover transition-all shadow-md shadow-brand/20"
            >
              Start Free Audit
            </button>
          </div>
        </div>
      </header>

      {/* 1. Hero Section */}
      <section className="relative pt-20 pb-24 px-6 max-w-5xl mx-auto text-center space-y-6">
        <div className="inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full bg-brand/10 border border-brand/20 text-brand text-xs font-bold tracking-wider uppercase">
          <span>AuditAI by Yample Labs</span>
          <span>•</span>
          <span>Analyze • Upgrade • Grow</span>
        </div>

        <h1 className="text-4xl sm:text-6xl font-black text-text-primary tracking-tight leading-tight">
          AI Website Intelligence Platform
        </h1>

        <p className="text-base sm:text-lg text-text-muted max-w-2xl mx-auto leading-relaxed">
          AuditAI combines automated Core Web Vitals scanning, WCAG AA accessibility checks, and AI business analysis to upgrade your website into a high-converting growth engine.
        </p>

        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
          <button
            onClick={() => setIsAuditModalOpen(true)}
            className="w-full sm:w-auto px-8 py-3.5 rounded-xl bg-brand text-white text-sm font-bold hover:bg-brand-hover transition-all shadow-lg shadow-brand/25 flex items-center justify-center space-x-2"
          >
            <span>⚡</span>
            <span>Start Free Audit</span>
          </button>
          <Link
            href="/sample-report"
            className="w-full sm:w-auto px-8 py-3.5 rounded-xl bg-surface border border-border text-sm font-bold text-text-primary hover:bg-surface/80 transition-all flex items-center justify-center space-x-2"
          >
            <span>📄</span>
            <span>View Sample Report</span>
          </Link>
        </div>
      </section>

      {/* 2. What AuditAI Does */}
      <section id="about" className="py-16 px-6 max-w-6xl mx-auto space-y-10 border-t border-border/60">
        <div className="text-center space-y-2">
          <h2 className="text-2xl sm:text-3xl font-extrabold text-text-primary">What AuditAI Does</h2>
          <p className="text-sm text-text-muted max-w-xl mx-auto">
            Comprehensive 360-degree website intelligence across every critical metric.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {whatAuditAiDoes.map((item) => (
            <div key={item.title} className="p-6 rounded-xl border border-border bg-card hover:border-brand/40 transition-all space-y-3">
              <span className="text-3xl">{item.icon}</span>
              <h3 className="text-base font-bold text-text-primary">{item.title}</h3>
              <p className="text-xs text-text-muted leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* 3. Why Choose Yample Labs */}
      <section className="py-16 px-6 max-w-6xl mx-auto space-y-10 border-t border-border/60">
        <div className="text-center space-y-2">
          <h2 className="text-2xl sm:text-3xl font-extrabold text-text-primary">Why Choose Yample Labs</h2>
          <p className="text-sm text-text-muted max-w-xl mx-auto">
            We don’t just run audits — we engineer production solutions that drive revenue.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {whyChooseYampleLabs.map((item) => (
            <div key={item.title} className="p-5 rounded-xl border border-border bg-card space-y-2">
              <h3 className="text-sm font-bold text-text-primary">{item.title}</h3>
              <p className="text-xs text-text-muted leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* 4. Our Services */}
      <section id="services" className="py-16 px-6 max-w-6xl mx-auto space-y-10 border-t border-border/60">
        <div className="text-center space-y-2">
          <h2 className="text-2xl sm:text-3xl font-extrabold text-text-primary">Our Agency Services</h2>
          <p className="text-sm text-text-muted max-w-xl mx-auto">
            Full-stack engineering services by Yample Labs to upgrade your digital presence.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {ourServices.map((service) => (
            <div key={service.title} className="p-6 rounded-xl border border-border bg-card space-y-3 relative overflow-hidden">
              {service.tag && (
                <span className="absolute top-3 right-3 px-2.5 py-0.5 rounded-full bg-brand/10 text-brand text-[10px] font-bold uppercase">
                  {service.tag}
                </span>
              )}
              <h3 className="text-base font-bold text-text-primary">{service.title}</h3>
              <p className="text-xs text-text-muted leading-relaxed">{service.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* 5. Pricing Tiers */}
      <section id="pricing" className="py-16 px-6 max-w-6xl mx-auto space-y-10 border-t border-border/60">
        <div className="text-center space-y-2">
          <h2 className="text-2xl sm:text-3xl font-extrabold text-text-primary">Transparent Pricing Packages</h2>
          <p className="text-sm text-text-muted max-w-xl mx-auto">
            Clear, fixed investment tiers for website upgrades and custom software development.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {pricingTiers.map((tier) => (
            <div
              key={tier.name}
              className={`p-8 rounded-2xl border ${
                tier.isPopular ? 'border-brand bg-card shadow-2xl shadow-brand/10 relative' : 'border-border bg-card'
              } flex flex-col justify-between space-y-6`}
            >
              {tier.isPopular && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full bg-brand text-white text-[10px] font-bold uppercase tracking-wider">
                  Most Popular
                </div>
              )}

              <div className="space-y-4">
                <h3 className="text-xl font-bold text-text-primary">{tier.name}</h3>
                <div className="flex items-baseline space-x-1">
                  <span className="text-3xl font-black text-text-primary">{tier.price}</span>
                </div>
                <p className="text-xs text-text-muted leading-relaxed">{tier.subtext}</p>

                <div className="pt-4 border-t border-border/60 space-y-2.5">
                  {tier.features.map((feat) => (
                    <div key={feat} className="flex items-center space-x-2 text-xs text-text-primary">
                      <span className="text-emerald-400 font-bold">✓</span>
                      <span>{feat}</span>
                    </div>
                  ))}
                </div>
              </div>

              <button
                onClick={() => setIsAuditModalOpen(true)}
                className={`w-full py-3 rounded-xl text-xs font-bold transition-all ${
                  tier.isPopular
                    ? 'bg-brand text-white hover:bg-brand-hover shadow-md shadow-brand/20'
                    : 'bg-surface border border-border text-text-primary hover:bg-surface/80'
                }`}
              >
                {tier.cta}
              </button>
            </div>
          ))}
        </div>
      </section>

      {/* 6. AI Assistant */}
      <section id="ai-assistant" className="py-16 px-6 max-w-6xl mx-auto space-y-10 border-t border-border/60">
        <div className="text-center space-y-2">
          <h2 className="text-2xl sm:text-3xl font-extrabold text-text-primary">24/7 AI Customer Assistant</h2>
          <p className="text-sm text-text-muted max-w-xl mx-auto">
            Automated lead collection, appointment support, and customer inquiries built into your website.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {aiAssistantFeatures.map((feat) => (
            <div key={feat.title} className="p-5 rounded-xl border border-border bg-card space-y-2">
              <h3 className="text-sm font-bold text-text-primary">{feat.title}</h3>
              <p className="text-xs text-text-muted leading-relaxed">{feat.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* 7. Sample Report Preview Section */}
      <section className="py-16 px-6 max-w-6xl mx-auto space-y-8 border-t border-border/60 text-center">
        <div className="space-y-2">
          <h2 className="text-2xl sm:text-3xl font-extrabold text-text-primary">Sample PDF Audit Report</h2>
          <p className="text-sm text-text-muted max-w-xl mx-auto">
            See the exact enterprise PDF report structure AuditAI generates for every audit.
          </p>
        </div>

        <div className="flex items-center justify-center space-x-4">
          <Link
            href="/sample-report"
            className="px-6 py-3 rounded-xl bg-brand text-white text-xs font-bold hover:bg-brand-hover transition-all shadow-md shadow-brand/20"
          >
            View Sample Report
          </Link>
          <a
            href="/api/reports/download?url=https://example.com&score=74"
            target="_blank"
            rel="noopener noreferrer"
            className="px-6 py-3 rounded-xl bg-surface border border-border text-xs font-bold text-text-primary hover:bg-surface/80"
          >
            Download Sample Report
          </a>
        </div>
      </section>

      {/* 8. Our Process */}
      <section id="process" className="py-16 px-6 max-w-6xl mx-auto space-y-10 border-t border-border/60">
        <div className="text-center space-y-2">
          <h2 className="text-2xl sm:text-3xl font-extrabold text-text-primary">Our 6-Step Growth Process</h2>
          <p className="text-sm text-text-muted max-w-xl mx-auto">
            From initial audit scan to long-term revenue scaling.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {ourProcess.map((step) => (
            <div key={step.step} className="p-6 rounded-xl border border-border bg-card space-y-3">
              <div className="text-2xl font-black text-brand">{step.step}</div>
              <h3 className="text-base font-bold text-text-primary">{step.title}</h3>
              <p className="text-xs text-text-muted leading-relaxed">{step.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* 9. Testimonials (Coming Soon) */}
      <section className="py-16 px-6 max-w-4xl mx-auto text-center space-y-4 border-t border-border/60">
        <h2 className="text-2xl font-extrabold text-text-primary">Client Testimonials</h2>
        <div className="p-8 rounded-2xl border border-border bg-card/60 space-y-2">
          <span className="text-brand font-bold text-xs uppercase tracking-wider">Coming Soon</span>
          <p className="text-xs text-text-muted max-w-md mx-auto">
            We hold strict standards for social proof. Verified client testimonials will be published here upon completion of active project phases.
          </p>
        </div>
      </section>

      {/* 10. FAQ Accordion */}
      <section className="py-16 px-6 max-w-4xl mx-auto space-y-8 border-t border-border/60">
        <div className="text-center space-y-2">
          <h2 className="text-2xl sm:text-3xl font-extrabold text-text-primary">Frequently Asked Questions</h2>
          <p className="text-sm text-text-muted">Everything you need to know about AuditAI & Yample Labs.</p>
        </div>

        <div className="space-y-3">
          {faqs.map((faq, idx) => (
            <div key={faq.q} className="rounded-xl border border-border bg-card overflow-hidden">
              <button
                onClick={() => setActiveFaq(activeFaq === idx ? null : idx)}
                className="w-full p-4 text-left font-semibold text-xs text-text-primary flex items-center justify-between hover:bg-surface/50"
              >
                <span>{faq.q}</span>
                <span className="text-brand font-bold">{activeFaq === idx ? '−' : '+'}</span>
              </button>
              {activeFaq === idx && (
                <div className="p-4 border-t border-border/40 text-xs text-text-muted leading-relaxed">
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* 11. Contact & Footer */}
      <footer id="contact" className="border-t border-border/80 bg-card/60 py-16 px-6">
        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8 mb-12">
          <div className="space-y-3">
            <div className="flex items-center space-x-2">
              <div className="h-7 w-7 rounded-lg bg-brand flex items-center justify-center font-bold text-white text-xs">
                A
              </div>
              <span className="font-bold text-base text-text-primary">AuditAI</span>
            </div>
            <p className="text-xs text-text-muted leading-relaxed">
              Flagship AI Website Intelligence Platform & Digital Agency by Yample Labs.
            </p>
          </div>

          <div>
            <h4 className="text-xs font-bold text-text-primary uppercase tracking-wider mb-3">Yample Labs Services</h4>
            <ul className="text-xs text-text-muted space-y-2">
              <li>Website Upgrades ($599+)</li>
              <li>Custom Web Development</li>
              <li>AI Automation & Bots</li>
              <li>Mobile App Engineering</li>
            </ul>
          </div>

          <div>
            <h4 className="text-xs font-bold text-text-primary uppercase tracking-wider mb-3">Official Links</h4>
            <ul className="text-xs text-text-muted space-y-2">
              <li><Link href="/sample-report" className="hover:text-text-primary">Sample PDF Report</Link></li>
              <li><Link href="/case-studies" className="hover:text-text-primary">Case Studies</Link></li>
              <li><Link href="/dashboard" className="hover:text-text-primary">Agency Dashboard</Link></li>
            </ul>
          </div>

          <div>
            <h4 className="text-xs font-bold text-text-primary uppercase tracking-wider mb-3">Contact & Support</h4>
            <ul className="text-xs text-text-muted space-y-2">
              <li>Email: <a href="mailto:yamplelabs@gmail.com" className="text-brand hover:underline">yamplelabs@gmail.com</a></li>
              <li>Instagram: <a href="https://instagram.com/yamplelabs" target="_blank" rel="noopener noreferrer" className="text-brand hover:underline">@yamplelabs</a></li>
              <li>Support & Feedback: <span className="text-text-primary font-semibold">@mannish_2323</span></li>
              <li>GitHub: <a href="https://github.com/manish63018-sketch" target="_blank" rel="noopener noreferrer" className="text-brand hover:underline">manish63018-sketch</a></li>
            </ul>
          </div>
        </div>

        <div className="max-w-6xl mx-auto pt-8 border-t border-border/40 flex flex-col sm:flex-row items-center justify-between text-[11px] text-text-muted gap-4">
          <div>© 2026 AuditAI by Yample Labs. All rights reserved.</div>
          <div className="flex items-center space-x-4">
            <span>Terms of Service</span>
            <span>•</span>
            <span>Privacy Policy</span>
          </div>
        </div>
      </footer>

      <QuickAuditModal isOpen={isAuditModalOpen} onClose={() => setIsAuditModalOpen(false)} />
    </div>
  )
}
