'use client'

import React from 'react'
import { motion } from 'framer-motion'
import { Globe, Cpu, FileText, Send } from 'lucide-react'

/**
 * How It Works Section — docs/02-UI-UX-Blueprint.md
 * 4-step process explaining the audit workflow
 */

const STEPS = [
  {
    step: '01',
    icon: Globe,
    title: 'Enter Any Website URL',
    description:
      'Paste any public website URL. AuditAI validates, fetches, and prepares the site for deep analysis — no installs or code changes required.',
    color: '#2563EB',
  },
  {
    step: '02',
    icon: Cpu,
    title: 'AI Runs the Full Audit',
    description:
      'Our AI engine simultaneously runs Performance, SEO, Accessibility, Security, and Technology scans — then passes the raw data to Claude, Gemini, and GPT for business analysis.',
    color: '#7C3AED',
  },
  {
    step: '03',
    icon: FileText,
    title: 'Get Business-Grade Reports',
    description:
      'Receive an Executive Summary, Technical Report, Developer Guide, and Client Proposal — all generated by AI and ready to download as professional PDFs.',
    color: '#22C55E',
  },
  {
    step: '04',
    icon: Send,
    title: 'Convert Insights into Clients',
    description:
      'Use the built-in CRM to track leads, send AI-generated cold emails, create proposals, and manage projects — all from one platform.',
    color: '#F59E0B',
  },
] as const

export function HowItWorks() {
  return (
    <section
      id="how-it-works"
      className="section relative overflow-hidden bg-background-card border-y border-border"
      aria-labelledby="how-it-works-heading"
    >
      {/* Background grid */}
      <div className="absolute inset-0 bg-grid-pattern opacity-60" aria-hidden="true" />

      <div className="container max-w-7xl mx-auto px-5 lg:px-8 relative">
        {/* Section header */}
        <div className="text-center mb-16">
          <motion.p
            className="text-sm font-semibold text-brand uppercase tracking-widest mb-3"
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
          >
            Simple Workflow
          </motion.p>
          <motion.h2
            id="how-it-works-heading"
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
          >
            From URL to{' '}
            <span className="gradient-text">Business Intelligence</span>{' '}
            in Minutes
          </motion.h2>
          <motion.p
            className="mt-4 text-lg text-text-secondary max-w-xl mx-auto text-balance"
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.2 }}
          >
            No complex setup. No integrations. Just a URL — and a complete
            website intelligence report.
          </motion.p>
        </div>

        {/* Steps */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 relative">
          {/* Connecting line (desktop) */}
          <div
            className="hidden lg:block absolute top-10 left-[calc(12.5%+1rem)] right-[calc(12.5%+1rem)] h-px"
            style={{
              background:
                'linear-gradient(90deg, #2563EB20, #2563EB60, #7C3AED60, #22C55E60, #F59E0B20)',
            }}
            aria-hidden="true"
          />

          {STEPS.map((step, index) => {
            const Icon = step.icon
            return (
              <motion.div
                key={step.step}
                className="relative flex flex-col items-center text-center"
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-60px' }}
                transition={{ duration: 0.4, delay: index * 0.1 }}
              >
                {/* Icon container */}
                <div
                  className="relative z-10 h-20 w-20 rounded-2xl flex items-center justify-center mb-5 border"
                  style={{
                    background: `${step.color}10`,
                    borderColor: `${step.color}30`,
                    boxShadow: `0 0 24px ${step.color}20`,
                  }}
                >
                  <Icon className="h-8 w-8" style={{ color: step.color }} aria-hidden="true" />
                  {/* Step number */}
                  <span
                    className="absolute -top-2 -right-2 h-6 w-6 rounded-full text-xs font-bold flex items-center justify-center border"
                    style={{
                      background: step.color,
                      borderColor: `${step.color}60`,
                      color: '#fff',
                    }}
                    aria-hidden="true"
                  >
                    {index + 1}
                  </span>
                </div>

                <h3 className="text-base font-semibold text-text-primary mb-3">
                  {step.title}
                </h3>
                <p className="text-sm text-text-secondary leading-relaxed">
                  {step.description}
                </p>
              </motion.div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
