'use client'

import Link from 'next/link'

export default function SampleReportPage() {
  return (
    <div className="min-h-screen bg-background text-text-primary p-6 md:p-12 space-y-8 max-w-5xl mx-auto">
      <div className="flex items-center justify-between border-b border-border/60 pb-6">
        <div>
          <Link href="/" className="text-xs text-brand hover:underline">
            ← Back to Yample Labs
          </Link>
          <h1 className="text-3xl font-bold text-text-primary tracking-tight mt-2">
            Sample Audit Report Preview
          </h1>
          <p className="text-sm text-text-muted mt-1">
            Real enterprise-grade PDF report format generated by AuditAI for clients.
          </p>
        </div>
        <div className="flex items-center space-x-3">
          <a
            href="/api/reports/download?url=https://example.com&score=74"
            target="_blank"
            rel="noopener noreferrer"
            className="px-5 py-2.5 rounded-lg bg-brand text-white text-xs font-semibold hover:bg-brand-hover transition-all shadow-md shadow-brand/20"
          >
            Download Sample HTML/PDF Report
          </a>
        </div>
      </div>

      {/* Embedded Live Report Preview Frame */}
      <div className="rounded-xl border border-border bg-card overflow-hidden shadow-2xl h-[750px]">
        <iframe
          src="/api/reports/download?url=https://example.com&score=74"
          className="w-full h-full border-none"
          title="Sample Audit Report Preview"
        />
      </div>
    </div>
  )
}
